/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

/**
 *
 * @author mateus garcia
 */
public class ajuda extends javax.swing.JFrame {

    /**
     * Creates new form ajuda
     */
    public ajuda() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MENU AJUDA");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Logar:\n{Tela de login}\no usuario deve por o usuario e a senha nos \ncampos indicados e clckar no botão entrar\n\nCriar Responsavel financeiro:\n{tela inicial do programa}\npara realizar um cadastro clique em cadastros\n{tela com cadastros clickado}\nClique em cadastrar novo responsavel financeiro\n{Tela mostrando a opção de escolher o tipo do responsavel juridico ou fisico}\nclique em sim para empresas e não para pessoas fisicas\n{tela com o formulario}\nAgora basta preencher o formulario e clicar em salvar\n\nCriar Paciente:\n{tela inicial do programa}\npara realizar um cadastro clique em cadastros\n{tela com cadastros clickado}\nClique em cadastrar novo Paciente\n{tela do formulario de cadastro de paciente}\nClique em escolha para selecionar o responsavel financeiro\n{Tela pedindo ID do responsavel financeiro}\nIntroduza o ID do responsavel financeiro e clique no botão ok\n{Tela com o formulario desbloqueado e o respFin escolhido}\nPreencha o formulario e clique em salvar\n\nAtiva\\Reativar cadastro:\n{tela inicial do programa}\npara realizar uma reativação\\reativação clique em cadastros\n{Tela com cadastros clicado}\nAgora clique em Ativar\\Inativar Cadastros\n{Tela que pede o ID}\nDigite o ID e clique em OK\n\nSAIR:\nclique em siste e logo após sair\n\ncomo achar a Ajuda:\nComo diabos você chegou aquie hein?\n\n{tela com cadastros clickado}");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
